
CREATE TABLE IF NOT EXISTS prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id INT NOT NULL,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    price_list VARCHAR(2) NOT NULL,
    product_id INT NOT NULL,
    priority INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    curr VARCHAR(3) NOT NULL,
    date_created TIMESTAMP,
    date_update TIMESTAMP
);
